cp ../A-tulympic/problem.pdf A-tulympic.pdf
cp ../B-interdimensional-thief/problem.pdf B-interdimensional-thief.pdf
cp ../C-zombieland/problem.pdf C-zombieland.pdf
cp ../D-ezproblem/problem.pdf D-ezproblem.pdf
cp ../E-sneaky-getaway/problem.pdf E-sneaky-getaway.pdf
cp ../F-abgift/problem.pdf F-abgift.pdf
cp ../G-final-crisis/problem.pdf G-final-crisis.pdf
cp ../H-forest-resorts/problem.pdf H-forest-resorts.pdf
cp ../I-mathmath/problem.pdf I-mathmath.pdf
cp ../J-isekai/problem.pdf J-isekai.pdf
cp ../K-precious-treasure/problem.pdf K-precious-treasure.pdf
cp ../L-autocomplete/problem.pdf L-autocomplete.pdf
